export const ADD_EXPERIMENT = 'ADD_EXPERIMENT'
export const UPDATE_EXPERIMENT = 'UPDATE_EXPERIMENT'
export const DELETE_EXPERIMENT = 'DELETE_EXPERIMENT'
export const CHANGE_EXPERIMENT_STATUS = 'CHANGE_EXPERIMENT_STATUS'
